#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jan 04, 2024 02:39:53 PM IST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import frame_builder_UI_support

_bgcolor = '#919191'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("776x565+384+164")
        top.minsize(1, 1)
        top.maxsize(1521, 930)
        top.resizable(1,  1)
        top.title("USB-C DB Frame Builder")
        top.configure(background="#919191")
        top.configure(highlightbackground="#919191")
        top.configure(highlightcolor="black")

        self.top = top

        self.Toutput = tk.Text(self.top)
        self.Toutput.place(relx=0.052, rely=0.637, relheight=0.241
                , relwidth=0.732)
        self.Toutput.configure(background="white")
        self.Toutput.configure(font="TkTextFont")
        self.Toutput.configure(highlightbackground="#919191")
        self.Toutput.configure(selectbackground="#d9d9d9")
        self.Toutput.configure(tabstyle="wordprocessor")
        self.Toutput.configure(undo="1")
        self.Toutput.configure(wrap="word")

        self.Bupdate = tk.Button(self.top)
        self.Bupdate.place(relx=0.052, rely=0.549, height=31, width=134)
        self.Bupdate.configure(activebackground="#d9d9d9")
        self.Bupdate.configure(background="#919191")
        self.Bupdate.configure(disabledforeground="#6d6d6d")
        self.Bupdate.configure(font="-family {DejaVu Sans} -size 10")
        self.Bupdate.configure(highlightbackground="#919191")
        self.Bupdate.configure(text='''Update Frame''')

        self.Bgenerate = tk.Button(self.top)
        self.Bgenerate.place(relx=0.052, rely=0.46, height=31, width=134)
        self.Bgenerate.configure(activebackground="#d9d9d9")
        self.Bgenerate.configure(background="#919191")
        self.Bgenerate.configure(disabledforeground="#6d6d6d")
        self.Bgenerate.configure(font="-family {DejaVu Sans} -size 10")
        self.Bgenerate.configure(highlightbackground="#919191")
        self.Bgenerate.configure(text='''Generate Frame''')

        self.LFcolorselect = tk.LabelFrame(self.top)
        self.LFcolorselect.place(relx=0.052, rely=0.177, relheight=0.251
                , relwidth=0.174)
        self.LFcolorselect.configure(relief='ridge')
        self.LFcolorselect.configure(font="-family {DejaVu Sans} -size 10")
        self.LFcolorselect.configure(relief="ridge")
        self.LFcolorselect.configure(text='''Color select''')
        self.LFcolorselect.configure(background="#919191")
        self.LFcolorselect.configure(highlightbackground="#919191")

        self.LFdisplayframe = tk.LabelFrame(self.top)
        self.LFdisplayframe.place(relx=0.271, rely=0.088, relheight=0.517
                , relwidth=0.513)
        self.LFdisplayframe.configure(relief='ridge')
        self.LFdisplayframe.configure(font="-family {DejaVu Sans} -size 10")
        self.LFdisplayframe.configure(relief="ridge")
        self.LFdisplayframe.configure(text='''Display Frame''')
        self.LFdisplayframe.configure(background="#919191")
        self.LFdisplayframe.configure(cursor="spraycan")
        self.LFdisplayframe.configure(highlightbackground="#919191")

        self.Lselcolor = tk.Label(self.top)
        self.Lselcolor.place(relx=0.052, rely=0.106, height=21, width=136)
        self.Lselcolor.configure(activebackground="#d9d9d9")
        self.Lselcolor.configure(background="#919191")
        self.Lselcolor.configure(compound='center')
        self.Lselcolor.configure(disabledforeground="#6d6d6d")
        self.Lselcolor.configure(font="-family {DejaVu Sans} -size 10")
        self.Lselcolor.configure(highlightbackground="#919191")
        self.Lselcolor.configure(relief="solid")
        self.Lselcolor.configure(text='''Selected color''')

        self.Mtitle = tk.Message(self.top)
        self.Mtitle.place(relx=0.327, rely=0.025, relheight=0.048
                , relwidth=0.344)
        self.Mtitle.configure(background="#919191")
        self.Mtitle.configure(font="-family {DejaVu Sans} -size 10")
        self.Mtitle.configure(highlightbackground="#919191")
        self.Mtitle.configure(justify='center')
        self.Mtitle.configure(padx="1")
        self.Mtitle.configure(pady="1")
        self.Mtitle.configure(text='''USB-C DB Frame Builder''')
        self.Mtitle.configure(width=202)

        self.LFselframe = tk.LabelFrame(self.top)
        self.LFselframe.place(relx=0.825, rely=0.088, relheight=0.788
                , relwidth=0.129)
        self.LFselframe.configure(relief='ridge')
        self.LFselframe.configure(font="-family {DejaVu Sans} -size 10")
        self.LFselframe.configure(relief="ridge")
        self.LFselframe.configure(text='''Frame select''')
        self.LFselframe.configure(background="#919191")
        self.LFselframe.configure(highlightbackground="#919191")

        self.LBselframe = tk.Listbox(self.LFselframe)
        self.LBselframe.place(relx=0.01, rely=0.04, relheight=0.951
                , relwidth=0.96, bordermode='ignore')
        self.LBselframe.configure(background="white")
        self.LBselframe.configure(disabledforeground="#6d6d6d")
        self.LBselframe.configure(font="TkFixedFont")
        self.LBselframe.configure(highlightbackground="#919191")
        self.LBselframe.configure(relief="ridge")
        self.LBselframe.configure(selectbackground="#d9d9d9")

        self.Bload = tk.Button(self.top)
        self.Bload.place(relx=0.606, rely=0.903, height=31, width=134)
        self.Bload.configure(activebackground="#d9d9d9")
        self.Bload.configure(background="#919191")
        self.Bload.configure(disabledforeground="#6d6d6d")
        self.Bload.configure(font="-family {DejaVu Sans} -size 10")
        self.Bload.configure(highlightbackground="#919191")
        self.Bload.configure(text='''Load Frame(s)''')

        self.Mmessages = tk.Message(self.top)
        self.Mmessages.place(relx=0.052, rely=0.903, relheight=0.051
                , relwidth=0.536)
        self.Mmessages.configure(anchor='w')
        self.Mmessages.configure(background="#919191")
        self.Mmessages.configure(font="-family {DejaVu Sans} -size 10")
        self.Mmessages.configure(highlightbackground="#919191")
        self.Mmessages.configure(padx="1")
        self.Mmessages.configure(pady="1")
        self.Mmessages.configure(relief="solid")
        self.Mmessages.configure(width=416)

def start_up():
    frame_builder_UI_support.main()

if __name__ == '__main__':
    frame_builder_UI_support.main()




